/* tslint:disable */
/**
 * @license
 * Copyright 2025 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 */
import {GoogleGenAI} from '@google/genai';

// Fix: Define and use AIStudio interface for window.aistudio to resolve type conflict.
// Define the aistudio property on the window object for TypeScript
declare global {
  interface AIStudio {
    openSelectKey: () => Promise<void>;
  }
  interface Window {
    aistudio?: AIStudio;
  }
}

async function openApiKeyDialog() {
  if (window.aistudio?.openSelectKey) {
    await window.aistudio.openSelectKey();
  } else {
    // This provides a fallback for environments where the dialog isn't available
    showStatusError(
      'API key selection is not available. Please configure the API_KEY environment variable.',
    );
  }
}

const statusEl = document.querySelector('#status') as HTMLDivElement;

// --- DOM Element Selection ---
const promptEl = document.querySelector('#prompt-input') as HTMLTextAreaElement;
const generateButton = document.querySelector(
  '#generate-button',
) as HTMLButtonElement;
const outputImage = document.querySelector('#output-image') as HTMLImageElement;
const imageInput = document.querySelector('#image-input') as HTMLInputElement;
const imagePreviewContainer = document.querySelector('#image-preview-container') as HTMLDivElement;
const imagePreview = document.querySelector('#image-preview') as HTMLImageElement;
const removeImageBtn = document.querySelector('#remove-image') as HTMLButtonElement;

// --- State Variables ---
let prompt = '';
let uploadedImage: { base64: string, mimeType: string } | null = null;

// --- Event Listeners ---
promptEl.addEventListener('input', () => {
  prompt = promptEl.value;
});

imageInput.addEventListener('change', () => {
  const file = imageInput.files?.[0];
  if (file) {
    const reader = new FileReader();
    reader.onload = (e) => {
      const result = e.target?.result as string;
      imagePreview.src = result;
      imagePreviewContainer.classList.remove('hidden');
      // Extract base64 data (remove 'data:image/xyz;base64,')
      const base64 = result.split(',')[1];
      uploadedImage = { base64, mimeType: file.type };
    };
    reader.readAsDataURL(file);
  }
});

removeImageBtn.addEventListener('click', () => {
  uploadedImage = null;
  imageInput.value = '';
  imagePreviewContainer.classList.add('hidden');
});

generateButton.addEventListener('click', () => {
  if (!prompt.trim()) {
    showStatusError('Please enter a prompt.');
    return;
  }
  generate();
});

// --- Functions ---
function showStatusError(message: string) {
  statusEl.innerHTML = `<span class="text-red-400">${message}</span>`;
}

function setControlsDisabled(disabled: boolean) {
  generateButton.disabled = disabled;
  promptEl.disabled = disabled;
  imageInput.disabled = disabled;
  removeImageBtn.disabled = disabled;
}

async function generateImage(prompt: string, apiKey: string) {
  const ai = new GoogleGenAI({apiKey});

  if (uploadedImage) {
    // Use Gemini 3 Pro Image Preview for editing/generation with image input
    const response = await ai.models.generateContent({
      model: 'gemini-3-pro-image-preview',
      contents: {
        parts: [
          { inlineData: { mimeType: uploadedImage.mimeType, data: uploadedImage.base64 } },
          { text: prompt }
        ]
      },
      config: {
        // We can add specific image config if needed, but default is usually fine.
      }
    });

    let imageFound = false;
    if (response.candidates?.[0]?.content?.parts) {
      for (const part of response.candidates[0].content.parts) {
        if (part.inlineData) {
          const base64ImageBytes = part.inlineData.data;
          const mimeType = part.inlineData.mimeType || 'image/png';
          const imageUrl = `data:${mimeType};base64,${base64ImageBytes}`;
          outputImage.src = imageUrl;
          outputImage.style.display = 'block';
          imageFound = true;
          break;
        }
      }
    }
    
    if (!imageFound) {
      const textPart = response.candidates?.[0]?.content?.parts?.find(p => p.text);
      if (textPart && textPart.text) {
        throw new Error(`Model returned text instead of image: ${textPart.text}`);
      }
      throw new Error('No image was generated by the model.');
    }

  } else {
    // Use Imagen for text-to-image generation
    const response = await ai.models.generateImages({
      model: 'imagen-4.0-generate-001',
      prompt,
      config: {
        // numberOfImages: 1,
        // outputMimeType: 'image/jpeg',
        // personGeneration: 'ALLOW_ADULT',
        // aspectRatio: '16:9',
        // imageSize: '1K',
      },
    });

    const images = response.generatedImages;
    if (images === undefined || images.length === 0) {
      throw new Error(
        'No images were generated. The prompt may have been blocked.',
      );
    }

    const base64ImageBytes = images[0].image.imageBytes;
    const imageUrl = `data:image/jpeg;base64,${base64ImageBytes}`;
    outputImage.src = imageUrl;
    outputImage.style.display = 'block';
  }
}

async function generate() {
  const apiKey = process.env.API_KEY;

  if (!apiKey) {
    showStatusError('API key is not configured. Please add your API key.');
    await openApiKeyDialog();
    return;
  }

  statusEl.innerText = 'Generating...';
  outputImage.style.display = 'none';
  setControlsDisabled(true);

  try {
    await generateImage(prompt, apiKey);
    statusEl.innerText = 'Generation successful.';
  } catch (e) {
    console.error('Generation failed:', e);
    const errorMessage =
      e instanceof Error ? e.message : 'An unknown error occurred.';

    let userFriendlyMessage = `Error: ${errorMessage}`;
    let shouldOpenDialog = false;

    if (typeof errorMessage === 'string') {
      if (errorMessage.includes('Requested entity was not found.')) {
        userFriendlyMessage =
          'Model not found. This can be caused by an invalid API key or permission issues. Please check your API key.';
        shouldOpenDialog = true;
      } else if (
        errorMessage.includes('API_KEY_INVALID') ||
        errorMessage.includes('API key not valid') ||
        errorMessage.toLowerCase().includes('permission denied')
      ) {
        userFriendlyMessage =
          'Your API key is invalid. Please add a valid API key.';
        shouldOpenDialog = true;
      }
    }

    showStatusError(userFriendlyMessage);

    if (shouldOpenDialog) {
      await openApiKeyDialog();
    }
  } finally {
    setControlsDisabled(false);
  }
}